"""Clients used by pipeline workflows."""

import os
import re
from pathlib import Path
from typing import Any, Dict, List

import requests

from auditengine.constants import EXCLUDE_DIRECTORIES, GITHUB_TOKEN, RUNTIME_USER
from auditengine.logger import get_logger
from auditengine.repo_tree_builder import build_project_file_tree_with_loc

logger = get_logger(__name__)


class GitHubActionClient:
    """Simplified GitHub API client for GitHub Actions environment."""

    def __init__(self):
        self.github_token = GITHUB_TOKEN
        if not self.github_token:
            raise ValueError("GITHUB_TOKEN environment variable required")

        self.headers = {
            "PRIVATE-TOKEN": f"{self.github_token}",
        }

        self.excluded_dirs = EXCLUDE_DIRECTORIES
        if self.excluded_dirs:
            logger.debug(f"Excluded directories: {self.excluded_dirs}")

    def get_pr_data(self, host: str, repo_name: str, pr_number: int) -> Dict[str, Any]:
        project_path = repo_name.replace("/", "%2F")

        pr_url = f"https://{host}/api/v4/projects/{project_path}/merge_requests/{pr_number}/changes"
        response = requests.get(pr_url, headers=self.headers, verify=False)
        response.raise_for_status()
        pr_data = response.json()

        def get_file_status(f: Dict[str, Any]) -> str:
            if f.get("new_file"):
                return "added"
            if f.get("deleted_file"):
                return "removed"
            if f.get("renamed_file"):
                return "renamed"
            return "modified"

        return {
            "number": pr_data.get("iid"),
            "title": pr_data.get("title", ""),
            "body": pr_data.get("description", ""),
            "user": pr_data.get("author", {}).get("name_cn", "Unknown"),
            "created_at": pr_data.get("created_at"),
            "updated_at": pr_data.get("updated_at"),
            "state": pr_data.get("state"),
            "head": {
                "ref": pr_data.get("source_branch", ""),
                "sha": pr_data.get("diff_refs", {}).get("head_sha", ""),
                "repo": {"full_name": repo_name},
            },
            "base": {
                "ref": pr_data.get("target_branch", ""),
                "sha": pr_data.get("diff_refs", {}).get("base_sha", ""),
            },
            "files": [
                {
                    "old_path": f.get("old_path", ""),
                    "new_path": f.get("new_path", ""),
                    "filename": f.get("file_path", ""),
                    "status": get_file_status(f),
                    "additions": f.get("added_lines", 0),
                    "deletions": f.get("removed_lines", 0),
                    "patch": f.get("diff", ""),
                }
                for f in pr_data.get("changes", [])
                if not self._is_excluded(f.get("file_path", ""))
            ],
            "additions": pr_data.get("added_lines", 0),
            "deletions": pr_data.get("removed_lines", 0),
            "changed_files": len(pr_data.get("changes", [])),
        }

    def _is_excluded(self, filepath: str) -> bool:
        for excluded_dir in self.excluded_dirs:
            normalized_excluded = excluded_dir[2:] if excluded_dir.startswith("./") else excluded_dir

            if filepath.startswith(excluded_dir + "/"):
                return True
            if filepath.startswith(normalized_excluded + "/"):
                return True
            if "/" + normalized_excluded + "/" in filepath:
                return True

        return False

    def _filter_generated_files(self, diff_text: str) -> str:
        file_sections = re.split(r"(?=^diff --git)", diff_text, flags=re.MULTILINE)
        filtered_sections = []

        for section in file_sections:
            if not section.strip():
                continue

            if (
                "@generated by" in section
                or "@generated" in section
                or "Code generated by OpenAPI Generator" in section
                or "Code generated by protoc-gen-go" in section
            ):
                continue

            match = re.match(r"^diff --git a/(.*?) b/", section)
            if match:
                filename = match.group(1)
                if self._is_excluded(filename):
                    logger.debug(f"Filtering out excluded file: {filename}")
                    continue

            filtered_sections.append(section)

        return "".join(filtered_sections)


class RepositoryScopeClient:
    """Repository scanner and exclusion matcher for full-repo mode."""

    def __init__(self):
        self.excluded_dirs = EXCLUDE_DIRECTORIES
        if self.excluded_dirs:
            logger.info(f"Excluded directories: {self.excluded_dirs}")

    def _is_excluded(self, filepath: str) -> bool:
        for excluded_dir in self.excluded_dirs:
            normalized_excluded = excluded_dir[2:] if excluded_dir.startswith("./") else excluded_dir

            if filepath.startswith(excluded_dir + "/"):
                return True
            if filepath.startswith(normalized_excluded + "/"):
                return True
            if "/" + normalized_excluded + "/" in filepath:
                return True

        return False

    def get_full_repo_data(self, repo_dir: Path, repo_name: str) -> Dict[str, Any]:
        files: List[Dict[str, Any]] = []
        repository_file_tree_with_loc = build_project_file_tree_with_loc(
            repo_dir=repo_dir,
            is_excluded=self._is_excluded,
        )

        for root, _, filenames in os.walk(repo_dir):
            root_path = Path(root)
            for filename in filenames:
                abs_path = root_path / filename
                rel_path = abs_path.relative_to(repo_dir).as_posix()
                if self._is_excluded(rel_path):
                    continue
                if "/.git/" in f"/{rel_path}/":
                    continue
                files.append(
                    {
                        "filename": rel_path,
                        "old_path": rel_path,
                        "new_path": rel_path,
                        "status": "existing",
                        "additions": 0,
                        "deletions": 0,
                        "patch": "",
                    }
                )

        return {
            "number": 0,
            "title": "Full repository security scan",
            "body": "Scan scope: full repository",
            "user": RUNTIME_USER,
            "created_at": None,
            "updated_at": None,
            "state": "full_scan",
            "head": {"ref": "full-repo", "sha": "", "repo": {"full_name": repo_name}},
            "base": {"ref": "", "sha": ""},
            "files": files,
            "additions": 0,
            "deletions": 0,
            "changed_files": len(files),
            "repository_path": str(repo_dir),
            "repository_file_tree_with_loc": repository_file_tree_with_loc,
            "scan_scope": "full_repository",
        }
